#+TITLE: Notes On Color Grading
#+LAYOUT: post
#+DATE:   2018-01-04 00:48:00 -0800
#+TAGS: color-grading editing film
#+liquid: enabled


* Source

This is a set of notes I compiled for my friend who was interested in making his videos look better. I figured this would make for an interesting post, so I'm copying it as sent.

* Notes on Coloring
   
** Pipeline
    
   Here's my typical node layout in Resolve if I'm doing a full color grade based off footage shot in S-Log2.

   - [ ] 3D-Lut - S-Log2 => Linear
   - [ ] Gain - .5
     - This removes the stop I overexpose shooting
   - [ ] 3D-Lut - Liner => Cineon
     - Want to be in log space for creative adjustments
   - [ ] Creative Grading
   - [ ] Filtering
     - Throw in a little dehaze/sharpening to taste
     - Maybe even a little grain if that's part of your feel
   - [ ] Cineon => Alex-X2
     - This gets us to a Rec709 output color space, but with those sweet Alexa colors and highlight rolloff

** Tools

*** [[https://www.blackmagicdesign.com/products/davinciresolve/][Da Vinci Resolve]]

    Awesome color grading software that is offered at an unfairly competitive price. A lot of features that you won't even know are there, hidden behind features which you will fight to get it to do what you want.

    Added a lot more editing and sound mixing tools recently, trying to become the only software you ever need to be in for a large domain of video projects.

    The addition of the OFX filters has really added in a lot of those good final look features that were missing and you needed to add after before. I'm personally in the middle of developing a very serious /thing/ for the Dehaze filter.

**** Premiere

     The Lumetri Color tools inside of premiere have gotten a lot better in recent updates. The controls are fast and flexible and can get a lot of good work done quickly, they just have hard limits where the stop working.
     Secondary grades can get to be more trouble than they're worth very quickly.

** Good Resources

*** [[https://cameramanben.github.io/LUTCalc/][LUTCalc]]

    This page is amazing! Let's you create custom color space transformation LUTs for just about any camera.

    This is the basis of my workflow shooting with the FS700 and Odyssey 7Q. I come out of the camera is S-Log2 exposed about a stop over. Then I make a LUT on this site that takes out the stop and flips over Alexa X-2 output. This is how I one light and quick color correct things.

    Has links to a lot of other great technical resources if you want to read white papers and get down into the nitty gritty of color science.

*** [[https://www.provideocoalition.com/aadams/][Art Adams' Blog]]
     
    He's this cool camera-man/blogger guy who works *ALOT*. He does a really good job of explaining the technical software aspects of creating a look.

    He's the one who turned me on to LUTCalc and incorporating that into a on-set/one-light workflow. Definitely read through his stuff for more information.

*** [[https://www.amazon.com/Print-Ansel-Adams-Photography/dp/0821221876][The Print - Ansel Adams]]
     
    Ansel Adams is one of the pioneers of photography as an art form. His work is breathtaking and the tools he had available were unbelievably shitty compared to what we have available today.

    He did this really awesome book series where he talks a lot about his technical process. This book talks about his work in the darkroom, which is very much related to color grading today. This was unbelievably insightful about what it is you are actually trying to accomplish when you go in to produce a final image.

    Talks a lot about exposure and how you're attempting to recreate a facsimile of something you actually witnessed and how the creative use of a limited dynamic range can be a metaphor for the emotion behind an experience beyond what actually occured.

*** [[https://www.fxphd.com/][fxphd]]

    That website we always took classes from together. They've got some really good color grading stuff on here, it just costs money.

    They changed their pricing model pretty recently, so I think if you pay the subscription fee you can look at all the old courses they have.
